### ISSUE TITLE
Wrong MP calculation combine in multicellular editor when editing two (or more) cell types in a row

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3413] opened 2022-06-15 03:50 UTC
To reproduce (for example)

1. Add two cell types (Stem, Stem2)
  ![image](https://user-images.githubusercontent.com/60734649/173732819-7d2605e2-83d8-4627-bcdd-41c6797b2cd0.png)

2. Modify Stem, delete Flagellum (The cost reads -2, but actually it costs 5)
![image](https://user-images.githubusercontent.com/60734649/173732904-d216a014-a5cf-41c6-85bf-9147f07db869.png)

3. Modify Stem2, add Flagellum
![image](https://user-images.githubusercontent.com/60734649/173733055-217c4a63-3026-4b3a-9c83-c7328f619f07.png)
MP goes to 98. ![image](https://user-images.githubusercontent.com/60734649/173733168-c858ef59-cdf9-4291-abb8-691cca82d581.png)

Debugging Info:
ActionHistory:![image](https://user-images.githubusercontent.com/60734649/173733487-94fb2a1d-366c-4168-9184-5075342798ac.png)
Combined:![image](https://user-images.githubusercontent.com/60734649/173733569-50a789ba-df0a-463e-8ed1-1f513f1e45bc.png)

Remove in one cell and Place in another is mis-combined to a move.

**Comment by Kashnox** [comment] 2023-10-02 00:01
I wasn't able to reproduce this on master. It might have been fixed with the recent changes to the multicellular editor in PR #4483 because we no longer allow combining actions from different contexts.

**Comment by buckly90** [comment] 2023-10-03 16:14
I was able to reproduce the bug playing the 0.6.3 release, but following the exact same steps on master fails to reproduce.

So yeah it seems this might not be an issue anymore.

**Comment by hhyyrylainen** [comment] 2023-10-04 06:34
Alright let's close this then as the new context feature of cell edits should now prevent this incorrect action combining from happening.

**Closed by hhyyrylainen** 2023-10-04 06:34 UTC
Labels: difficult, programming, review, bug, C#, stage:multicellular

**Comment by hhyyrylainen** [comment] 2024-04-10 07:22
A new probable variant of this bug: https://github.com/Revolutionary-Games/Thrive/issues/5010
