### ISSUE TITLE
Cytoplasm organelles

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#348] opened 2015-11-06 19:28 UTC

**Comment by Moopli** [comment] 2015-12-03 21:08
1-hex organelle which provides a small amount of storage and a small amount of glycolysis, and can be overwritten directly by placing another organelle on top.

**Comment by Moopli** [comment] 2015-12-03 21:27
May as well add a few other things to this one:

* New compound, pyruvate
* New process, glycolysis: 1 glucose -> 2 pyruvate + 2 ATP
* Modify respiration process to: 1 pyruvate + 3 oxygen -> 3 CO2 + 18 ATP
* Make all organelles able to perform a small amount of glycolysis, scaled by number of hexes they take up (since they all sit in cytoplasm)

We might have to account for electron carriers (like NAD+/NADH) too, but for now no reason to worry about it.

**Comment by TheCreator--** [comment] 2015-12-04 04:25
This seems like a duplicate of #291.

**Comment by Moopli** [comment] 2015-12-04 04:34
It is and I will merge contents, thank you

**Closed by Moopli** 2015-12-04 04:34 UTC
Labels: easy, lua, programming
