### ISSUE TITLE
Cell processes tab fails to update after dying

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#3897] opened 2022-12-02 19:46 UTC
**Describe the bug**
Values and processes shown in the cell processes tab will fail to update after dying or reproducing

Made more noticable with the day and night cycle system, as you can clearly see the sunlight% not changing

The amount of sunlight displayed in the cell processes tab, will fail to update after dying, displaying the same amount that it was before

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any patch with light (preferably one with 100%)
2. Add a photosynthetic organelle to your cell
3. Confirm and check cell processes, focus on photosynthesis
4. Close cell processes tab
5. Commit suicide
6. Check cell processes again, the sunlight% will not update after respawning, causing a misleading glucose gain amount to be displayed

**Expected behaviour**
The sunlight% should update after I die, displaying the correct amount
![Process1](https://user-images.githubusercontent.com/33234241/205374000-7ca31e30-ed19-4294-8f58-5f34a03654f2.png)
Commiting suicide, going extinct and moving to a new patch
![Process2](https://user-images.githubusercontent.com/33234241/205374010-527a5c2e-6346-4a5b-8f24-b1a1f7be4354.png)

**Screenshots**

**Additional context**
I moved to a new patch after dying, but the same bug still happens if you stay in the same patch

**Comment by Oliveriver** [comment] 2022-12-02 20:05
I've already discovered that this (or at least, the same situation but reproducing instead of dying) isn't a regression caused by the day/night cycle, and in fact the process panel doesn't update at all after reproducing. It's just that having sunlight changing makes it much more visible.

**Comment by hhyyrylainen** [comment] 2022-12-02 21:33
Reading the title I was reminded that I forgot to open the issue for the process panel not updating, which I did now: https://github.com/Revolutionary-Games/Thrive/issues/3898 Did I remember the issue right, @Oliveriver ? If these problems are just variants of each other, one of these should be closed.

**Comment by Oliveriver** [comment] 2022-12-02 21:52
Yes, that’s correct, and it seems likely the two are related as both involve a change of life state for the player cell.

**Comment by hhyyrylainen** [comment] 2022-12-03 08:24
I renamed my other issue a bit and added the extra info. I'll close this as a duplicate so that the other issue can be the one tracking all problems related to the process panel not updating.

**Closed by hhyyrylainen** 2022-12-03 08:24 UTC
