### ISSUE TITLE
AI cells sometimes splitting into more than two cells

### ISSUE THREAD

**Issue by Arty-Taiga** [Revolutionary-Games/Thrive#3289] opened 2022-04-30 00:00 UTC
sometimes when i am playing the game, i see at the corner or sides of the screen a cell suddenly become 6-18ish new cells. this ends up overpoplating and breaking my game if i do not move to a new patch in under 10 minutes. I've also seen AI cells of my own species do this. I don't know if this is a planned feature or not but my computer can not handle it. i've seen 1 cell become like 20+ cells and lagging my game.

**Comment by hhyyrylainen** [comment] 2022-04-30 07:40
I'm pretty sure that AI cells cannot reproduce with resources magically appearing, instead if they find a bit of (or many chunks) with a ton of resources they can absorb those very fast to get enough resources for multiple divisions. 0.5.8.1 will have despawning fixes that will keep game entity counts from getting out of hand. So based on that I'll close this but feel free to reopen if you have something to show with that there is an actual issue where cells can split without having the necessary resources to do so or splitting accidentally spawning 2 copies when it should have made just one, but as I said I quite doubt that either of those happen.

**Closed by hhyyrylainen** 2022-04-30 07:40 UTC

**Comment by Leinourdian** [comment] 2022-04-30 09:06
I'm guessing Arty-Taiga is talking about bacterial colonies. They are groups of cells that spawn together but one cell at a time, so they can kinda look like splitting. They mostly spawn off-screen but big ones can spawn partially on-screen as well. They can cause some lag but again the despawning fixes help with that. Maybe the on-screen spawns look weird to some people?

**Comment by hhyyrylainen** [comment] 2022-04-30 09:07
That also could be it, it'd be nice to make sure the colonies don't spawn so near the player that they'd be visible on screen when popping in. I've also noticed that large iron chunks sometimes pop into existence where the player can see them.

**Comment by Arty-Taiga** [comment] 2022-05-02 01:19
yeah, i have also seen compounds and iron chunks spawing in on the edge of the screen (this is also at max zoom) maybe increase the spawning distance for this stuff. I'll see if i can get a recording of this when i get home tonight and i'll post it here when i'm done
