### ISSUE TITLE
Explicit order of cell budding during multicellular stage

### ISSUE THREAD

**Issue by the-vindicar** [Revolutionary-Games/Thrive#3668] opened 2022-08-06 11:39 UTC
Growth pattern of a multicellular organism can be quite important, because due to specialization some cells might not be self-sustaining in terms of glucose or other ATP sources. Currently the cells bud in the same order they were added in the editor, and the only way to change the growth pattern of your organism is to delete every cell except the stem and then recreate them in desired order.
While it makes sense, it's rather inconvenient and MP costly operation, especially if you want to change the early stages of a creature approaching macro stage. Swapping the order of two cells should at least cost the same, regardless of whether those are 'early' or 'late' cells.

As such, I suggest that:
1. Cell growth order is shown explicitly in the multicellular editor
2. A reordering operation is added, analogous to move/delete operations. It should have a flat MP cost, as opposed to the current method.

**Comment by hhyyrylainen** [comment] 2022-08-06 12:15
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3206

**Closed by hhyyrylainen** 2022-08-06 12:15 UTC
