### ISSUE TITLE
The game is unable to be saved (idk if this has already been reported)

### ISSUE THREAD

**Issue by Szilverfox** [Revolutionary-Games/Thrive#3933] opened 2022-12-11 19:08 UTC
**The bug**

When i try to save the game it just sends an error massage.

**Screenshots**
![kép](https://user-images.githubusercontent.com/120333803/206923777-7d5defbc-b422-4f51-b290-550b31479bf2.png)

**System info (please complete the following information):**
- OS: windows 7 Proffesional
- Graphics card GeForce GT 630

- Thrive version 0.6.0 (but i encountered this bug in everyone of the versions i played)

**The full error massage**
Error Saving - Saving failed! An exception happened exception: System.ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.
  at (wrapper managed-to-native) System.Reflection.RuntimeAssembly.get_code_base(System.Reflection.Assembly,bool)
  at System.Reflection.RuntimeAssembly.GetCodeBase (System.Reflection.Assembly a, System.Boolean escaped) [0x00000] in <c84d94161bca414384015e66544862cf>:0 
  at System.Reflection.RuntimeAssembly.get_CodeBase () [0x00000] in <c84d94161bca414384015e66544862cf>:0 
  at System.Reflection.AssemblyName.Create (System.Reflection.Assembly assembly, System.Boolean fillCodebase) [0x00010] in <c84d94161bca414384015e66544862cf>:0 
  at System.Reflection.RuntimeAssembly.GetName (System.Boolean copiedName) [0x0000e] in <c84d94161bca414384015e66544862cf>:0 
  at System.Reflection.Assembly.GetName () [0x00000] in <c84d94161bca414384015e66544862cf>:0 
  at TypeUtils.AssemblyQualifiedNameWithoutVersion (System.Type type) [0x00011] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x0015b] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary (Newtonsoft.Json.JsonWriter writer, System.Collections.IDictionary values, Newtonsoft.Json.Serialization.JsonDictionaryContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0017b] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0013e] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary (Newtonsoft.Json.JsonWriter writer, System.Collections.IDictionary values, Newtonsoft.Json.Serialization.JsonDictionaryContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0017b] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0013e] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type rootType) [0x00008] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at BaseThriveConverter.WriteMember (System.String name, System.Object memberValue, System.Type memberType, System.Type objectType, Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializer serializer) [0x00012] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00197] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x0023a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x0000e] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at ThriveJsonConverter+<>c__DisplayClass10_0.<SerializeObject>b__0 (Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at ThriveJsonConverter.PerformWithSettings[T] (System.Func`2[T,TResult] func) [0x00068] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at ThriveJsonConverter.PerformWithSettings[T] (System.Func`2[T,TResult] func) [0x000a5] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at ThriveJsonConverter.SerializeObject (System.Object object, System.Type type) [0x00014] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Save.SaveToFile () [0x0000b] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at SaveHelper.PerformSave (InProgressSave inProgress, Save save) [0x00025] in <d71a57cf26f14bb49473d772acbd134a>:0

**Comment by hhyyrylainen** [comment] 2022-12-11 19:19
This is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1729

**Closed by hhyyrylainen** 2022-12-11 19:19 UTC
