### ISSUE TITLE
Crashing when clicking on undo button in cell editor

### ISSUE THREAD

**Issue by Styx6** [Revolutionary-Games/Thrive#4208] opened 2023-03-03 14:51 UTC
### Describe the bug

Crashes while modifying cell when you click undo in the multicellular stage editor.

### To Reproduce

1. Reach multicellular stage
2. Go to editor
3. Modify cell
4. Add a part
5. Click undo
6. Crash

### Expected behaviour

I expected it to undo and remove the part I added when clicking the undo button.

### System information

- Operating System: EndeavourOS Linux x86_64 _(Arch based)_
- Graphics Card: OpenGL ES 3.0 Renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
- Version: Thrive  0.6.1

### Game Logs

https://pastebin.com/4Tzgr5SL

**Comment by hhyyrylainen** [comment] 2023-03-03 15:53
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3836

**Closed by hhyyrylainen** 2023-03-03 15:53 UTC
