### ISSUE TITLE
Previous autosave overwrite doesn't work correctly if 1 auto save is kept

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1545] opened 2020-08-16 08:18 UTC
If you set the number of auto saves to keep in options to 1, then on save a new auto save is created each time, instead of overwriting the previous one. The logic for detecting the next auto save to write to probably has a bug when there is one existing auto save that should be overwritten.

Same issue might be in quick saves.

**Comment by DTanxxx** [comment] 2020-08-18 21:56
Hi hhyyrylainen,
I think I have found where the issue is. In InProgressSave class the GetNextNameForSaveType method has a check for 'If all slots aren't used yet' then create a new save, otherwise 'Replace oldest'. It seems that the if statement only checks for whether the number of quick saves has reached its max, and not for the number of auto saves.
`// If all slots aren't used yet
        if (totalCount < Settings.Instance.MaxQuickSaves || oldestSave == null)
        {
            ++highestNumber;
            return $"{newNameStart}_{highestNumber:n0}." + Constants.SAVE_EXTENSION;
        }

        // Replace oldest
        return oldestSave;`

I think the issue can be resolved by reconstructing the condition to:
`if ( (newNameStart == "quick_save" && totalCount < Settings.Instance.MaxQuickSaves) || 
       (newNameStart == "auto_save" && totalCount < Settings.Instance.MaxAutoSaves) ||
       (oldestSave == null) )`
where newNameStart is the parameter of the method being passed in either "auto_save" or "quick_save"

**Comment by DTanxxx** [comment] 2020-08-18 21:59
I tried to use the 'Insert code' option in comments but it seems I couldn't include the part starting from "// If all slots aren't used yet..." to "...+ Constants.SAVE_EXTENSION; }"

**Comment by hhyyrylainen** [comment] 2020-08-19 06:22
Yeah, looks like use of `Settings.Instance.MaxQuickSaves` in `GetNextNameForSaveType` is a bug.
It should be changed so that the method takes in the max count so that the caller can give the right value instead of trying to do a string comparison which might break in the future.

**Closed** 2020-08-20 08:08 UTC
Labels: C#, easy, programming, saving
