### ISSUE TITLE
Popups (like tutorials) are interactive when game is paused

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2576] opened 2021-09-05 06:16 UTC
> I was able to interact with the tutorial pop-up in the master branch as well. Hope this helps!
> 
> _Originally posted by @sirdanforth in https://github.com/Revolutionary-Games/Thrive/issues/2387#issuecomment-911839842_

**Comment by hhyyrylainen** [comment] 2021-09-05 07:18
This is pretty much a duplicate of https://github.com/Revolutionary-Games/Thrive/issues/2326 as I think the issue is the GUI layering where the popup panels for mouse events act like they are on top of the pause menu while they should be underneath it in the GUI input order (like they are visually).

**Closed by hhyyrylainen** 2021-09-05 07:18 UTC
