### ISSUE TITLE
Spamming  `Detected compound amount... to 0.`

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3294] opened 2022-04-30 12:07 UTC
Loads of NaN report for Iron and Hydrogen Sulfide, every time I get into a colony.
[Colony_Crash_2.zip](https://github.com/Revolutionary-Games/Thrive/files/8596857/Colony_Crash_2.zip)

**Comment by hhyyrylainen** [comment] 2022-04-30 12:37
This is duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3201
Could you post that info there as well?

**Closed by hhyyrylainen** 2022-04-30 12:37 UTC
