### ISSUE TITLE
Random error thrown after saving.

### ISSUE THREAD

**Issue by TheNamesGregoryAndounuts** [Revolutionary-Games/Thrive#2024] opened 2021-01-09 17:07 UTC
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our community forums:
https://community.revolutionarygamesstudio.com/

**Describe the bug**
When I pressed the DNA button to do... move on (I think) and the game tries to save it prints an error message. 

**To Reproduce**
(Shrug) not sure what I did myself if I'm honest...

**Expected behavior**
A clear and concise description of what you expected to happen, instead of what actually
happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/71222468/104103811-0f4ccf80-529c-11eb-95c3-cec57ad743d0.png)

**System info (please complete the following information):**
- OS: Windows 10 Home
- Graphics card: Intel HD graphics 405 4.4.0 (Onboard GPU)
- Thrive version: 5.3

**Logs**
https://pastebin.com/gcXK9YR9
```
Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
```

**Additional context**
N/A

**Comment by Kasterisk** [comment] 2021-01-09 17:17
Duplicate of #2014 so closing.

**Closed by Kasterisk** 2021-01-09 17:17 UTC
