### ISSUE TITLE
Auto-evo should take digestion into account

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#3512] opened 2022-07-12 17:46 UTC
Such as number of lysosomes present in a species affecting digestion speed and efficiency and what type of enzymes are contained by the species for deciding what can or can't be eaten. All these should be taken into account by the auto-evo.

**Comment by hhyyrylainen** [comment] 2022-08-03 06:13
This is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3358

**Closed by hhyyrylainen** 2022-08-03 06:13 UTC
Labels: intermediate, programming, C#
