### ISSUE TITLE
Cloud mixing brightness sometimes flickers (new with Godot 3.3)

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2275] opened 2021-05-30 04:15 UTC
**Describe the bug**
After switching to 0.5.4.0-alpha I noticed common rendering flashes appear when two material cloud spread together, a new problem I've never seen before.

**Screenshots**
A short clip here:
<https://1drv.ms/v/s!AmQa4DeAoN8FlXXsiXqHHQqR3UXH?e=NAPsaA>

**System info (please complete the following information):**
Windows 10 21H1 x64; RX 580 2048SP; 0.5.4.0-alpha

**Comment by Kasterisk** [comment] 2021-05-30 06:25
Could be related to #1700

**Comment by hhyyrylainen** [comment] 2021-05-30 07:25
If this is actually the compound clouds flashing their brightness quite quickly and in a random manner, this is definitely a duplicate.

**Comment by hhyyrylainen** [comment] 2021-05-30 09:24
I'll close this as a presumed duplicate of https://github.com/Revolutionary-Games/Thrive/issues/1700

**Comment by 84634E1A607A** [comment] 2021-05-30 14:33
Well, but this really isn't. I've noticed earlier beightness flashes, but that was caused only when the cloud was really big. 
This time when I'm using the latest version, I can see two kinds of compound clouds at the same place, **Not mixed together**, so it came exchanging the colors rapidly. 

For example, Ammonia Cloud and Iron Cloud got together but not mixed, Then the color switches between orange and dark red.

**Comment by hhyyrylainen** [comment] 2021-05-30 14:36
Could you make a video of it happening? Compound cloud mixing works on my end:
![2021-05-30_17 35 21 0977](https://user-images.githubusercontent.com/3796411/120108353-7eed2980-c16d-11eb-87c7-d385df5abb98.png)

**Comment by 84634E1A607A** [comment] 2021-05-30 14:40
There's already a link above.

**Comment by 84634E1A607A** [comment] 2021-05-30 14:41
I think it's because we switched to Godot 3.3

**Comment by hhyyrylainen** [comment] 2021-05-30 14:42
Ah, yeah, I see the video. Yeah, it looks like a different kind of flashing, this is still likely related to: #1700 even if this isn't the exact same problem.

**Comment by hhyyrylainen** [comment] 2021-05-31 19:33
After playing the latest version, I noticed that this basically always happens with iron clouds, but other cloud types seem to work fine, for some reason. Also this is very noticeable now, so fixing this is quite a big priority for the next release...

**Closed** 2021-06-01 16:08 UTC
Labels: difficult, engine, help wanted, programming
