### ISSUE TITLE
Give bonus starting resources to fully formed early multicellular colonies

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4237] opened 2023-03-20 12:50 UTC
Right now with the latest changes those fully spawned colonies get just a bit of resources based on the first cell, which is nowhere close to being enough for them to survive. Instead we need to either give them bonus resources on spawn or modify the early multicell initial resource collection to multiply the resources with the cell count. That latter thing needs also one more tiny tweak to ensure not too many initial compounds are given to the player for example when the player spawns as a non-full colony to make sure that initial resources aren't leaked as clouds.

**Comment by ottoblep** [comment] 2023-03-21 23:43
I don't think this can be fixed by just increasing the compounds of the first cell, since it's storage capacity is small most of the time. These are some additional possible solutions i came up with:
 - Adding additional starting resources for each new cell _+ low effort - unrealistic_
 - Player can decide when to reproduce and can stockpile resources in anticipation _+ realistic - high effort_
 - Add compounds to reproduction cost so a new cell will not spawn before the player has collected enough for it to survive. _+ realistic + low effort_

**Closed** 2023-09-21 08:23 UTC
Labels: easy, programming, C#, stage:multicellular
