### ISSUE TITLE
Undo Feature does not revert Slider Changes right

### ISSUE THREAD

**Issue by punctdan** [Revolutionary-Games/Thrive#2040] opened 2021-01-13 09:41 UTC
Undo button should take one shot to make you go back to previous value on sliders. However Undo does not revert the changes like this. It takes a few clicks on the button to go back to previous value as it only gets a little bit closer to that value every time you undo.

1. Go to Microbe Editor.
2. Go to Appearance tab.
3. Move Fluidity/Rigidity slider from default value to far left or right using mouse in one shot.
4. Tap Undo button once to see if it goes back to default value.

When you use the slider, you move it by holding it with right mouse button and release it at the value you're satisfied with. This takes the slider from one value to another value. Therefore Undo should not gradually move the slider to but directly to the previous value.

![2021-01-13_12 36 51 7690](https://user-images.githubusercontent.com/46677171/104434674-8a63fd80-559c-11eb-903a-9df1c4d0708a.png)
![2021-01-13_12 37 01 3457](https://user-images.githubusercontent.com/46677171/104434682-8b952a80-559c-11eb-941d-30a29877d5e5.png)
![2021-01-13_12 37 07 5075](https://user-images.githubusercontent.com/46677171/104434684-8c2dc100-559c-11eb-81ab-3d95be785c08.png)
![2021-01-13_12 37 13 2352](https://user-images.githubusercontent.com/46677171/104434687-8cc65780-559c-11eb-94ae-c829542fd629.png)

**Comment by hhyyrylainen** [comment] 2021-01-13 09:44
While this is a better named issue, this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1496
as combining subsequent changes into a single action will have the effect of making it a single undo step.

**Closed by hhyyrylainen** 2021-01-13 09:44 UTC
