### ISSUE TITLE
[Bug] [0.5.0-beta] Strange graphical boxing

### ISSUE THREAD

**Issue by Doomsdayrs** [Revolutionary-Games/Thrive#1242] opened 2020-05-11 18:10 UTC
**Describe the bug**
When swimming around in pools of nutrition, noticeable boxing occurs to pools

**To Reproduce**
1. Play game
2. Move to large swath of nutrition
3. After moving around, see lines that form large boxes

**Expected behavior**
Smooth transition between these 'boxes'

**Screenshots**
![image](https://user-images.githubusercontent.com/38189170/81595093-e8966c00-938f-11ea-8ea0-db5b8798689c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Graphics card: RX Vega 8
 - Thrive version: 0.5.0-beta

**Logs**
https://pastebin.com/6wmcKyY4

**Comment by hhyyrylainen** [comment] 2020-05-11 18:12
duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1194

**Closed by hhyyrylainen** 2020-05-11 18:12 UTC
