### ISSUE TITLE
Population Overflowed...

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2213] opened 2021-05-05 02:33 UTC
**Important**
Please only submit technical bug reports here. This is not a place to make feature requests
or suggestions. For that please visit our community forums:
https://community.revolutionarygamesstudio.com/

**Describe the bug**

As it is

**To Reproduce**
1. Just keep replicating and the population will overflow...

**Expected behavior**
A clear and concise description of what you expected to happen, instead of what actually
happened.

**Screenshots**

![image](https://user-images.githubusercontent.com/60734649/117090853-16887380-ad8c-11eb-9164-56562a607ba9.png)

**System info (please complete the following information):**
Same as my previous issue

**Comment by hhyyrylainen** [comment] 2021-05-05 05:49
I think this might be just the graph display, because internally the population numbers are `long`s so that should be no way near.
So this might be purely about the graphs, @Kasterisk ?
If so this would be a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/2197

**Comment by Kasterisk** [comment] 2021-05-06 08:28
Yeah this is caused by the data types used for the graphs not being sufficiently big, closing as we already have #2197.

**Closed by Kasterisk** 2021-05-06 08:28 UTC
Labels: review
