### ISSUE TITLE
Compound panel indicator goes crazy

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#1525] opened 2020-08-13 04:18 UTC
If a cell(the player or any other organism) is over some compound clouds, and you hover your cursor over it, the panel showing what compounds are at the cursor starts adding and removing compounds very quickly.

**Comment by hhyyrylainen** [comment] 2020-08-13 05:33
I think this is probably caused by a loop of venting and absorbing the compounds back. Can probably be fixed by adding a minimum amount to vent code or for the actual under cursor display to ignore small values.

**Closed** 2021-11-06 10:50 UTC
Labels: intermediate, programming, gui, bug
