### ISSUE TITLE
Pressing on extinct species in auto-evo explorer report doesn't show information about this species

### ISSUE THREAD

**Issue by TheESN** [Revolutionary-Games/Thrive#5435] opened 2024-08-31 12:06 UTC
It only shows info about species that didn't extinct at the moment in tree

I selected this one
![изображение](https://github.com/user-attachments/assets/735c2f3e-9b0a-44e2-be82-56103718ff38)

When I tried to select extinct one it didn't update info
![изображение](https://github.com/user-attachments/assets/e63effa7-1eb8-4399-863b-59d98b6f07f6)

**Comment by hhyyrylainen** [comment] 2024-08-31 12:08
I *think* this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/4977

**Comment by TheESN** [comment] 2024-08-31 12:09
I updated my comment to make more clear

**Comment by hhyyrylainen** [comment] 2024-08-31 12:11
Alright, I see this is a different bug. I'll add the labels for this now. Probably still quite related to that other issue as it is also about looking up species info but not finding it for extinct species (which I think is because extinct species are cleaned up to not hang around forever in the game data, though it should be possible to find them in the historical data and retrieve them for display).

**Comment by TheESN** [comment] 2024-08-31 12:22
I'll play a bit and try to check if this appears in main game too

**Comment by TheESN** [comment] 2024-08-31 12:51
Looks like it works fine inside game's Trivepedia

**Comment by hhyyrylainen** [comment] 2024-11-26 19:47
This should be fixed in the next Thrive release (0.8.0) so testing when that is out would be nice (or if you have devbuilds access / can build from source you can test now).

**Closed** 2024-11-26 19:46 UTC
Labels: intermediate, programming, bug, C#, stage:microbe
