### ISSUE TITLE
[0.5.2.0] 'Myr' have a glitch

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#1866] opened 2020-11-20 18:50 UTC
**Describe the bug**
When 'Myr' is with 5 digits, the second number from left to right shows a question mark.

**To Reproduce**
1. Play for some time...
2. Open the Report Tab.

**Expected behavior**
'Myr' should display the correct number.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/68707872/99838446-d2a10980-2b71-11eb-81e0-94b5b34e3b63.png)

**System info (please complete the following information):**
- OS: [Windows 7 SP1 x64]
- Graphics card: AMD Radeon R7 250
- Thrive version [0.5.2.0]

**Comment by hhyyrylainen** [comment] 2020-11-20 18:55
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1702

**Closed by hhyyrylainen** 2020-11-20 18:55 UTC
