### ISSUE TITLE
error loading libraries

### ISSUE THREAD

**Issue by Yottaqubyter** [Revolutionary-Games/Thrive#588] opened 2018-06-28 09:15 UTC
ERROR: /home/yottaqubyter/Escritorio/Thrive Launcher-linux-x64/installed/LINUX_Thrive.0.3.4/Thrive-0.3.4/bin/Thrive: error while loading shared libraries: libilbc.so.0: cannot open shared object file: No such file or directory
child process exited with code 127

**Comment by Yottaqubyter** [comment] 2018-06-28 09:16
P.D.: I'm on ubuntu

**Comment by hhyyrylainen** [comment] 2018-06-28 10:15
This is a duplicate of https://github.com/Revolutionary-Games/Thrive/issues/513

**Closed by hhyyrylainen** 2018-06-28 10:15 UTC
