### ISSUE TITLE
Crash on autosave.

### ISSUE THREAD

**Issue by samrrr** [Revolutionary-Games/Thrive#4069] opened 2023-01-28 16:32 UTC
**Describe the bug**

Crash on save on long games(30+ evo step one cell).

```
exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'PlacedOrganelle'.
  at Godot.Object.GetPtr (Godot.Object instance) [0x0001c] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
  at Godot.Object.ToString () [0x00000] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
  at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x0037e] in <c84d94161bca414384015e66544862cf>:0 
  at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00023] in <c84d94161bca414384015e66544862cf>:0 
  at System.String.Format (System.String format, System.Object arg0) [0x00008] in <c84d94161bca414384015e66544862cf>:0 
  at NodeGroupSaveHelper.WriteGroups (Newtonsoft.Json.JsonWriter writer, Godot.Node value, Newtonsoft.Json.JsonSerializer serializer) [0x00059] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseNodeConverter.WriteCustomExtraFields (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00000] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00264] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type rootType) [0x00008] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at BaseThriveConverter.WriteMember (System.String name, System.Object memberValue, System.Type memberType, System.Type objectType, Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializer serializer) [0x00012] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00197] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type rootType) [0x00008] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at BaseThriveConverter.WriteMember (System.String name, System.Object memberValue, System.Type memberType, System.Type objectType, Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializer serializer) [0x00012] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00197] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type rootType) [0x00008] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at BaseThriveConverter.WriteMember (System.String name, System.Object memberValue, System.Type memberType, System.Type objectType, Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializer serializer) [0x00012] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00197] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type rootType) [0x00008] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at BaseThriveConverter.WriteMember (System.String name, System.Object memberValue, System.Type memberType, System.Type objectType, Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializer serializer) [0x00012] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00197] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type rootType) [0x00008] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at BaseThriveConverter.WriteMember (System.String name, System.Object memberValue, System.Type memberType, System.Type objectType, Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonSerializer serializer) [0x00012] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at BaseThriveConverter.WriteJson (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.JsonSerializer serializer) [0x00242] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable (Newtonsoft.Json.JsonWriter writer, Newtonsoft.Json.JsonConverter converter, System.Object value, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00071] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x0023a] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.Formatting formatting, Newtonsoft.Json.JsonSerializerSettings settings) [0x0000e] in <f5c4580481df43759ebf446d5ffb33c1>:0 
  at ThriveJsonConverter+<>c__DisplayClass10_0.<SerializeObject>b__0 (Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at ThriveJsonConverter.PerformWithSettings[T] (System.Func`2[T,TResult] func) [0x00068] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at ThriveJsonConverter.PerformWithSettings[T] (System.Func`2[T,TResult] func) [0x000a5] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at ThriveJsonConverter.SerializeObject (System.Object object, System.Type type) [0x00014] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at Save.SaveToFile () [0x0000b] in <d71a57cf26f14bb49473d772acbd134a>:0 
  at SaveHelper.PerformSave (InProgressSave inProgress, Save save) [0x00025] in <d71a57cf26f14bb49473d772acbd134a>:0 
```

**System info (please complete the following information):**
- OS: Windows 10
- GeForce RTX 3090
- Thrive version 0.6.0

**Logs**

https://pastebin.com/mYPxjzL6

**Comment by hhyyrylainen** [comment] 2023-01-28 18:50
This looks like a duplicate of https://github.com/Revolutionary-Games/Thrive/issues/3911 to me, where in both the case is that the player cell has a reference to an object it is trying to engulf (is stored in attemptingToEngulf list) but it is disposed.

**Closed by hhyyrylainen** 2023-01-28 18:50 UTC
