### ISSUE TITLE
Intel graphics 620 GPU Works in 4.1.1 or Earlier, But not 4.2/4.3

### ISSUE THREAD

**Issue by niveis** [Revolutionary-Games/Thrive#956] opened 2020-03-11 16:07 UTC
I don't know WHERE to put this, But here's how i found out.
1: I start up thrive 4.3
2: It crashes
3: Start up 4.2
4: Same thing
5: Start up 4.1.1
6: It works!
7: Try it on 4.0.
8: It works!
So i think there's a change between 4.1.1 and 4.2, Something that makes intel GPUs throw a fit, If anyone has a clue, Please tell me.

**Comment by hhyyrylainen** [comment] 2020-03-11 16:13
0.4.2 switched to a new graphics engine.
This is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/804

**Closed by hhyyrylainen** 2020-03-11 16:13 UTC
