### ISSUE TITLE
Cell chunks can be engulfed with a pilus in the multicellular stage, even if the cell with the pilus has a membrane that can't engulf

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#3761] opened 2022-09-06 19:53 UTC
**Describe the bug**

If your multicellular organism contains another cell with a pilus and the player enters engulfment mode, cell chunks can be engulfed with the pilus even if the cell has a membrane that does not allow engulfing. The ingested material is transferred to the player cell

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter the early multicellular prototype
2. Create a new cell with a pilus and add it to your organism
3. Kill a cell with the pilus
4. Enter engulfment mode and ingest the cell chunks with the added cell's pilus
4. See the cell chunks being ingested and being transferred to the player cell

**Expected behaviour**
The added cell should not be able to engulf chunks with its pilus if it has a membrane that disallows engulfment

**Additional context**
[The bug can be seen in action in this video at 20:32](https://www.youtube.com/watch?v=fcG1mqGMi0c)

**Comment by hhyyrylainen** [comment] 2022-09-06 20:07
Game logs or something? I'm pretty certain that this is just a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3760 because I'm pretty sure if the pilus is bigged so that when a pilus hits something it is able to engulf it. So based on that this must be an effect of the physics engine giving us a bad collision index and we just attribute the collision to the colony lead cell (and not any pilus) so there's no way at that point to know that the hit was a pilus and should be ignored.

**Closed by hhyyrylainen** 2022-09-06 20:07 UTC

**Comment by stoptakingusernames** [comment] 2022-09-06 20:09
I opened two issues as these seem like two separate bugs

**Comment by hhyyrylainen** [comment] 2022-09-06 20:11
That's fine, you couldn't have known about this interconnected especially as I never bothered to open an issue placeholder for this problem in the first place, because there's nothing we can do and even Godot devs seem to be gearing up to replace the physics engine entirely in the Godot engine version 4.

**Comment by stoptakingusernames** [comment] 2022-09-06 20:24
I checked through the logs, I can confirm that this indeed is a physics issue
