### ISSUE TITLE
Add an options menu

### ISSUE THREAD

**Issue by Untrustedlife** [Revolutionary-Games/Thrive#650] opened 2018-12-15 18:06 UTC
We need to add an options menu so we can alter sound volume in game instead of having to hardcode every single thing related to  sound ever because thats messy and i hate having to do that.

**Comment by hhyyrylainen** [comment] 2018-12-15 18:41
This is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/509

**Closed by hhyyrylainen** 2018-12-15 18:41 UTC
Labels: AngelScript, C++, JavaScript, intermediate, programming
