### ISSUE TITLE
[0.5.3.0] Save Error

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2023] opened 2021-01-09 16:13 UTC
**Describe the bug**
Both autosave and manual save give the same error: **Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.**

**To Reproduce**
I attached both my log and autosave file which should give this error.

**Expected behavior**
This error never happened to me on 0.5.2.0 as far as I know (I played it for more than 30 generations).

**System info (please complete the following information):**
- OS: Windows 7 SP1 x64 bit
- Graphics card: AMD Radeon R7 250
- Thrive version: 0.5.3.0

**Logs**
[save error.txt](https://github.com/Revolutionary-Games/Thrive/files/5791377/save.error.txt)

**Additional context**
[auto_save_1.zip](https://github.com/Revolutionary-Games/Thrive/files/5791379/auto_save_1.zip)

EDIT: Maybe it's a duplicate of #2014.

**Comment by Kasterisk** [comment] 2021-01-09 17:05
Along with the reports on discord, this at least confirms that the FloatingChunk disposed error is still happening.

**Comment by hhyyrylainen** [comment] 2021-01-09 18:37
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1877

**Closed by hhyyrylainen** 2021-01-09 18:37 UTC
Labels: C#, bug, difficult, programming, saving
