### ISSUE TITLE
Investigate if turning on asynchronous shader compiling improves performance

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3735] opened 2022-08-19 03:16 UTC
Noticed that there's an option [`rendering/gles3/shaders/shader_compilation_mode`](https://docs.godotengine.org/en/3.5/classes/class_projectsettings.html#class-projectsettings-property-rendering-gles3-shaders-shader-compilation-mode) and it looks like turning this on can save compile time.

**Comment by hhyyrylainen** [comment] 2022-08-19 06:56
This is basically a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3678 as the ubershader is what stands in for a normal shader while it is being compiled.

**Closed by hhyyrylainen** 2022-08-19 06:56 UTC
