### ISSUE TITLE
Game locks up randomly with message Error: Attempt to disconnect a non existent connection from 'root,Window#32044483792>'

### ISSUE THREAD

**Issue by stevehello166** [Revolutionary-Games/Thrive#5081] opened 2024-04-29 14:57 UTC
### Describe the bug

Game locks up randomly with music still playing in the background and this message in launcher:
 Error: Attempt to disconnect a non existent connection from 'root,Window#32044483792>' 
Signal: 'focus entered', callable:"
 at: _disconnect(core/object/object.cpp:1420)

### To Reproduce

I'm not entirely sure it just happens while playing randomly

### Expected behaviour

For thrive to not freeze

### System information

- OS: Linux Mint Cinnamon 21.3 Virginia
- Thrive: 0.6.6.0
- Distribution method: Flatpak
- Graphics: Nvidia 1660 super with proprietary driver version 545.29.06 on X11
- CPU: Intel Core i5-2500 @ 3.4 MHz Sandy Bridge rev 7

### Game Logs

https://pastebin.com/XuVudJs3

**Comment by hhyyrylainen** [comment] 2024-04-29 15:06
I'm pretty sure the message is unrelated which just happens to be the last error printed (this is already on our Godot 4 issue board: https://github.com/Revolutionary-Games/Thrive/issues/5082 I just converted that to an issue but it had been an open item for 3 weeks already). 

Assuming that, then this issue is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/5072 Do you agree or do you think there's something different?

To help narrow down this issue, could you screenshot the game performance options that are set? Especially I'd like to know: if multithreaded game simulation is on and what the current game threads + native thread counts are. As I no longer see this game locking up on my computer I think it is thread count or CPU speed related.

**Comment by stevehello166** [comment] 2024-04-29 15:27
My performance settings:
![image](https://github.com/Revolutionary-Games/Thrive/assets/77701792/70280415-506c-4c8a-8775-0033540179c4)
It might have something to do with the first issue you mentioned(5082) because of the low thread counts of my CPU, but I'm not sure.

**Comment by hhyyrylainen** [comment] 2024-04-29 15:29
Thanks for the info, I'm hoping that by testing the various thread counts I can get the problem to happen on my computer. For now I'll assume this is a duplicate issue.

**Closed by hhyyrylainen** 2024-04-29 15:29 UTC
