### ISSUE TITLE
Game crash when occupying (0, 0) with nucleus, undo, and then add something where once occupied by the nucleus

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2296] opened 2021-06-05 12:04 UTC
**Describe the bug**
Game crash with exception:

```
E 0:01:35.803   IntPtr Godot.Object.GetPtr(Godot.Object ): System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'NucleusMesh'.
  <C++ Error>   Unhandled exception
  <C++ Source>  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs:37 @ IntPtr Godot.Object.GetPtr(Godot.Object )()
  <Stack Trace> Object.base.cs:37 @ IntPtr Godot.Object.GetPtr(Godot.Object )()
                Node.cs:538 @ void Godot.Node.RemoveChild(Godot.Node )()
                SceneDisplayer.cs:28 @ void SceneDisplayer.LoadNewScene()()
                SceneDisplayer.cs:20 @ void SceneDisplayer.set_Scene(System.String )()
                MicrobeEditor.cs:2120 @ void MicrobeEditor.UpdateOrganellePlaceHolderScene(SceneDisplayer , System.String )()
                MicrobeEditor.cs:2096 @ void MicrobeEditor.UpdateAlreadyPlacedVisuals()()
                MicrobeEditor.cs:2002 @ void MicrobeEditor.OnOrganellesChanged()()
                MicrobeEditor.cs:1431 @ void MicrobeEditor.UpdateEditor(Single )()
                MicrobeEditor.cs:620 @ void MicrobeEditor._Process(Single )()
```

When I add a nucleus that occupies (0, 0), use undo button to remove it, and then add something where the nucleus had been, the game crash.

**Screenshots**

** Full Log**
```
--- Debugging process started ---
Godot Engine v3.3.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon RX 580 2048SP
OpenGL ES Batching: ON
 
Loaded registry for Compound with 11 items
Loaded registry for MembraneType with 6 items
Loaded registry for Background with 11 items
Loaded registry for Biome with 11 items
Loaded registry for BioProcess with 13 items
Loaded registry for OrganelleDefinition with 17 items
Loaded registry for MusicCategory with 3 items
Loaded registry for HelpTexts with 5 items
Loaded registry for NamedInputGroup with 6 items
Loaded registry for Gallery with 3 items
SimulationParameters loading ended
SimulationParameters are good
This is Thrive version: 0.5.4.0-alpha
user:// directory is: C:/Users/admin/AppData/Roaming/Thrive
Game logs are written to: C:/Users/admin/AppData/Roaming/Thrive/logs latest log is 'log.txt'
Doing delayed apply for some settings
Jukebox now playing from: Menu
Jukebox: starting track: res://assets/sounds/main-menu-theme-1.ogg position: 0
Previous patch doesn't exist, despawning all entities.
Applying patch (Pangonian Vents) settings
Number of clouds in this patch = 8
Registering new spawner: Name: ammonia density: 4E-05
Registering new spawner: Name: glucose density: 2E-05
Registering new spawner: Name: phosphates density: 4E-05
Registering new spawner: Name: hydrogensulfide density: 4E-05
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Registering new spawner: Name: FLOATING_HAZARD density: 0.0001
Registering new spawner: Name: SMALL_IRON_CHUNK density: 5E-05
MARINE_SNOW spawn density is 0. It won't spawn
Registering new spawner: Name: BIG_IRON_CHUNK density: 5E-05
Number of species in this patch = 1
Registering new spawner: Name: 1 density: 1.438849E-05
Player Microbe spawned
Jukebox now playing from: MicrobeStage
TaskExecutor started with parallel job count: 6
Jukebox: starting track: res://assets/sounds/microbe-theme-6.ogg position: 0
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 0
Move to editor pressed
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 100000000
Applying auto-evo results
Starting microbe editor with: 1 organelles in the microbe
Editor action is now: cytoplasm
Jukebox now playing from: MicrobeEditor
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-3.ogg position: 0
Editor action is now: nucleus
Placing organelle 'nucleus' at: 0, 0
Replacing cytoplasm at: 0, 0
MicrobeEditor: applying changes to edited Species
MicrobeEditor: updated organelles for species: Primum Thrivium
MicrobeEditor: edited species name is now Primum Thrivium
Applying patch (Pangonian Vents) settings
Number of clouds in this patch = 8
Spawn frequency of glucose changed from 2 to 1
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
Number of chunks in this patch = 4
MARINE_SNOW spawn density is 0. It won't spawn
Number of species in this patch = 2
Registering new spawner: Name: 2 density: 1.428673E-05
Jukebox now playing from: MicrobeStage
Jukebox: starting track: res://assets/sounds/microbe-theme-6.ogg position: 2.7922
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 2.7922
Jukebox now playing from: Menu
Jukebox: starting track: res://assets/sounds/main-menu-theme-2.ogg position: 0
Previous patch doesn't exist, despawning all entities.
Applying patch (Pangonian Vents) settings
Number of clouds in this patch = 8
Registering new spawner: Name: ammonia density: 4E-05
Registering new spawner: Name: glucose density: 2E-05
Registering new spawner: Name: phosphates density: 4E-05
Registering new spawner: Name: hydrogensulfide density: 4E-05
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Registering new spawner: Name: FLOATING_HAZARD density: 0.0001
Registering new spawner: Name: SMALL_IRON_CHUNK density: 5E-05
MARINE_SNOW spawn density is 0. It won't spawn
Registering new spawner: Name: BIG_IRON_CHUNK density: 5E-05
Number of species in this patch = 1
Registering new spawner: Name: 1 density: 1.438849E-05
Player Microbe spawned
Jukebox now playing from: MicrobeStage
Jukebox: starting track: res://assets/sounds/microbe-theme-6.ogg position: 5.39864
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 5.39864
Move to editor pressed
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 100000000
Applying auto-evo results
Starting microbe editor with: 1 organelles in the microbe
Editor action is now: cytoplasm
Jukebox now playing from: MicrobeEditor
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-3.ogg position: 5.880454
Editor action is now: nucleus
Placing organelle 'nucleus' at: 0, 1
Replacing cytoplasm at: 0, 0
Editor action is now: chromatophore
Placing organelle 'chromatophore' at: 0, 0
--- Debugging process stopped ---
```

**Comment by hhyyrylainen** [comment] 2021-06-05 12:07
Is this a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/1961 ?
Undoing and placing the nucleus again causes the game to crash anyway. I think this is just a variant of that bug, namely that placing other organelles than the nucleus after undoing the nucleus crashes the game as well. So I'll close this as a duplicate of that. Is that okay with you?

**Closed by hhyyrylainen** 2021-06-05 12:07 UTC

**Comment by 84634E1A607A** [comment] 2021-06-05 12:10
Yes. Sure.
