### ISSUE TITLE
macOS Crash on Startup

### ISSUE THREAD

**Issue by rothn** [Revolutionary-Games/Thrive#3221] opened 2022-04-15 02:24 UTC
On the latest master (commit 45075307798d04de0300cfd62c6d88671b2030dc), when I build with `ruby make_release.rb -t "Mac OSX"`, the resulting .app always crashes on startup.

Note that the game works as expected when launched from Visual Studio (even in release) or from Godot_mono.

The issue cause seems to be related to this:
```
System.DllNotFoundException: /Users/nroth/Thrive/builds/Thrive_0.5.8.0-rc1_mac_osx 2/Thrive.app/Contents/MacOS/../Resources/GodotSharp/Mono/lib/../lib/libmono-native.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <6a7c203f6f7a4f07b7fa766077730d49>:0 
   --- End of inner exception stack trace ---
```

Which seems exactly the same as this Unity bug that was fixed in early 2022:
https://forum.unity.com/threads/build-issue-m1.1216383/
https://issuetracker.unity3d.com/issues/m1-webgl-editor-throws-errors-when-building-for-webgl-on-native-apple-silicon-editor

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the repo at 45075307798d04de0300cfd62c6d88671b2030dc and follow setup_instructions.md
2. Run `ruby make_release.rb -t "Mac OSX"`
3. Extract the .zip file from builds/ and run the app
4. Experience the error

**Expected behaviour**
The game should start up properly

**Logs**

```
Startup log: https://pastebin.com/zAfw0Hrn
```

**Comment by hhyyrylainen** [comment] 2022-04-15 06:59
I guess there is some kind of problem when exporting from a mac to mac? That's not something I've tried. I always make the releases for mac from Linux, and those builds seem to work, at least when used through the launcher when rosetta is used.
I've marked this as engine bug as it doesn't really seem like this is Thrive's fault.

**Comment by MutatingFunc** [comment] 2022-04-18 10:39
Hi! I've got a similar problem of being unable to start the game. I have Apple Silicon Mac, so I can't use Windows via Bootcamp.

---

### Releases are broken

@hhyyrylainen mentions the launcher is available for Mac. Does the Github link include the launcher?

The macOS download links on Github don't work for me (macOS 12.3.1, M1). The last two releases can't be launched, showing "This application is damaged and can't be opened". Toggling Rosetta doesn't seem to have any effect, I don't think it launches in the first place. Yet it sounds like it was working fine for others 3 days ago?

---

### Exported builds via Godot crash on launch

I've tried setting up the project locally and everything seems to run fine in debug builds. (Yay I can play!)

When I try to export the project as a standalone app using Godot, the error dialog gives me the crash report linked here: [https://pastebin.com/GixR4PGz](https://pastebin.com/GixR4PGz).

Snippet:
```
Application Specific Information:
*** multi-threaded process forked ***
crashed on child side of fork pre-exec
terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
```

Releases that still build, which includes everything back to December 2021, all have the same issue. August 2021's release doesn't build for me.

It looks as if Thrive could be responsible for this crash, but function names are missing from the stack trace. Having followed the setup instructions I can build in VS, but not run. Do you have instructions for how I could run a release build connected to Godot or Visual Studio, to get a proper stack trace and see what's going on?

---

- Am I being stupid?
- Are there any extra steps to run release builds?
- If no to both, I can open separate issues for each of the above.

**Comment by hhyyrylainen** [comment] 2022-04-18 10:47
The launcher should run on latest mac OS: https://github.com/Revolutionary-Games/Thrive-Launcher/releases
I've tested it on my m1 mac mini. You just need to get around the fact that the app is not signed so apple really doesn't want you to run the software.

I remember some people having problems with using the default zip extraction in mac for the Thrive releases, because it seems that apple's zip extractor will intentionally break extracted apps. Using something like 7zip to extract the .zip releases of Thrive on mac, has worked in the past to make things runnable.

**Comment by hhyyrylainen** [comment] 2022-04-18 10:50
Those apple crash reports don't seem very useful at all, perhaps Godot developers could be able to find out what went wrong, but I don't know. Much more useful would be the game output in terminal, it seems the process exits by calling `terminate` so it might be a controlled crash that would print an error message first.

**Comment by MutatingFunc** [comment] 2022-04-18 11:27
Here's the output running via Terminal: https://pastebin.com/P96PvyLU

Good news, it seems @rothn 's issue is reproducable. I'm getting the same issue:
```

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /Applications/Thrive_0.5.8.0_mac_osx/Thrive.app/Contents/MacOS/../Resources/GodotSharp/Mono/lib/../lib/libmono-native.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
```

**Comment by hhyyrylainen** [comment] 2022-04-18 12:15
Seems like a mono issue (fails to load the C# system dll file)? I plan on updating the Godot version we use pretty soon, which might help. But yeah, this seems to me almost 100% certain to be an engine issue.

**Comment by rothn** [comment] 2022-04-23 18:41
> Hi! I've got a similar problem of being unable to start the game. I have Apple Silicon Mac, so I can't use Windows via Bootcamp.
> 
> ### Releases are broken
> @hhyyrylainen mentions the launcher is available for Mac. Does the Github link include the launcher?
> 
> The macOS download links on Github don't work for me (macOS 12.3.1, M1). The last two releases can't be launched, showing "This application is damaged and can't be opened". Toggling Rosetta doesn't seem to have any effect, I don't think it launches in the first place. Yet it sounds like it was working fine for others 3 days ago?
> 
> **Resolution**: Don't use the macOS Archive Utility to unzip and it's fine. Also get the launcher.
> 
> ### Exported builds via Godot crash on launch
> I've tried setting up the project locally and everything seems to run fine in debug builds. (Yay I can play!)
> 
> When I try to export the project as a standalone app using Godot, the error dialog gives me the crash report linked here: https://pastebin.com/GixR4PGz.
> 
> Snippet:
> 
> ```
> Application Specific Information:
> *** multi-threaded process forked ***
> crashed on child side of fork pre-exec
> terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
> 
> Kernel Triage:
> VM - pmap_enter failed with resource shortage
> VM - pmap_enter failed with resource shortage
> VM - pmap_enter failed with resource shortage
> ```
> 
> Releases that still build, which includes everything back to December 2021, all have the same issue. August 2021's release doesn't build for me.
> 
> It looks as if Thrive could be responsible for this crash, but function names are missing from the stack trace. Having followed the setup instructions I can build in VS, but not run. Do you have instructions for how I could run a release build connected to Godot or Visual Studio, to get a proper stack trace and see what's going on?
> 
> **Update**: Found to be the same issue as upthread.
> 
> * Am I being stupid?
> * Are there any extra steps to run release builds?
> * If no to both, I can open separate issues for each of the above.

This looks like a separate issue. Extracting with the `7z` command allows the Thrive.app file to still run. macOS Archive Manager does something weird with the zip files under releases. Perhaps some missing signature? Regardless, this seems to be something else.

**Comment by hhyyrylainen** [comment] 2022-04-23 18:55
> Perhaps some missing signature? 

We are currently not paying apple and are because of that not a registered developer so we can't sign our apps for mac.

**Comment by hhyyrylainen** [comment] 2022-05-09 17:33
This should be fixed now. Turns out I had to turn off the hardened runtime option and export the game from a mac to make things work (I found that info here: https://github.com/godotengine/godot/issues/56392).

I opened a PR with my changes which I'll merge once people can confirm the launcher can now download the new version of 0.5.8.1 (you need to delete the previous install to download the new file).

**Closed** 2022-05-10 07:33 UTC
Labels: difficult, programming, engine, bug, help wanted
