### ISSUE TITLE
Pause menu shouldn't open at extinction

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2898] opened 2021-12-04 10:00 UTC
Now that Extinction theme has LoadGame button and ReturnToMenu Button

1. The LoadGame button produces a LoadMenu, but you can pause in it: 
![image](https://user-images.githubusercontent.com/60734649/144705400-bbb77d1c-f955-43c4-b0e6-9a97328b8949.png)

2. There's no need to pause when you are extinct...

**Comment by hhyyrylainen** [comment] 2021-12-04 10:32
There is actually a reasonable expectation that the player might want to view the game statistics once they are extinct. So I think it makes sense to still allow opening the full pause menu even when extinct. And also hiding the pause button etc. I think is unnecessary complexity. If other people also feel that this issue is worth it, we can reopen this, but I'll close this for now as unnecessary feature.

**Closed by hhyyrylainen** 2021-12-04 10:32 UTC

**Comment by RacerBG** [comment] 2021-12-04 10:34
How about adding only the "Statistics" button to the extinction screen?

**Comment by 84634E1A607A** [comment] 2021-12-04 10:35
What about this? Two LoadMenu...

![image](https://user-images.githubusercontent.com/60734649/144706392-5057ad79-e305-4d7e-8f0d-77a929821f58.png)

**Comment by hhyyrylainen** [comment] 2021-12-04 10:35
I think having too many buttons on it isn't a good idea. This entire problem is kind of even caused by adding any buttons at all. But I think overall having the exit and load buttons is a good idea because many players seemed to get stuck for too long on the extinction screen as they didn't realize to press the menu button.
