### ISSUE TITLE
Cell orientation recovers slowly after physics turning it

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#721] opened 2019-01-24 11:18 UTC
When playing as a prokaryote if you collide with another cell you can often get turned so that the cell is no longer pointing at the cursor.

Here is a video of the bug: https://www.youtube.com/watch?v=ZER4SlxuWIQ

**Comment by hhyyrylainen** [comment] 2019-01-24 20:31
I marked this as difficult and non-gating as I'm not sure what the problem might be.

**Comment by Untrustedlife** [comment] 2019-01-29 19:48
So after looking through the code the only thing i could think of is that, this his happening because the starter cells mass is now at 0.1, when it used to be 1 , due to the nucleus, so you get knocked around alot easier, you couldn't see it before because your cell was heavy enough and you cant see where bacteria actually intend to go, so in my branch i have now set the base mass of the cell to 0.7 (which is the nucelus's mass), and i seem to have much better control over my cell now.

**Comment by Untrustedlife** [comment] 2019-01-29 19:51
But i dont know if this is a actual proper fix until the bug happens, so we leave this open. There is nothing in the movement code that should have been changed with the dev builds  other then the nucleus not being actually in the middle of the cell anymore, this may also have to do with it.

**Comment by Untrustedlife** [comment] 2019-01-29 20:31
@TjWhale even though its not happening to you anymore i wont close it yet just be be safe, if no ones runs into the issue this week i'll close this and the gyrating issue. :)

**Comment by hhyyrylainen** [comment] 2019-01-29 20:52
It's strange that the orientation setting could wouldn't almost instantly correct the incorrect heading (as it is lerping each frame to the target)

**Comment by crodnu** [comment] 2019-02-16 00:51
I think the problem might be caused by an object rotating the microbe (in this case the bacteria) while a orientation is being set, which might cause weird behavior (since physics engines usually don't like you setting orientations manually)

**Closed** 2020-04-17 12:23 UTC
Labels: AngelScript, difficult, programming
