### ISSUE TITLE
Spawning in the cell colony

### ISSUE THREAD

**Issue by Gameboy555r** [Revolutionary-Games/Thrive#4098] opened 2023-02-02 16:17 UTC
### Describe the bug

So after exiting the early multicellular editor i spawned inside my last cell colony and because of that my fps count went from 60 to 15 drasticly, somebody take a look in this problem

### Expected behaviour

I expect to spawn outside of my last colony like 2 meters away to avoid the fps loss. 

### Screenshots

Not avaible due to the lags.

### System information

-Os windows 11
-procesor 2.0 Ghz

### Game Logs

.

### Additional Context

none

**Comment by hhyyrylainen** [comment] 2023-02-03 08:36
I'm pretty sure this is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3653

Especially based on the expected behaviour you mentioned:
> I expect to spawn outside of my last colony like 2 meters away to avoid the fps loss.

**Closed by hhyyrylainen** 2023-02-03 08:36 UTC
