### ISSUE TITLE
When I start a new game without using tutorial I'm not able to modify my specie

### ISSUE THREAD

**Issue by AndreLZGava** [Revolutionary-Games/Thrive#572] opened 2018-05-31 16:39 UTC
When I start a new game if I choose to use tutorial I'm not able to modify my organism. If I choose to use tutorial I can modify. After modify my organism it become with 0 ATP as soon I'll die (I must start with full life and full APT).

**Comment by hhyyrylainen** [comment] 2018-05-31 16:53
I'm not exactly sure what is your issue. Not getting to edit your cell before playing if you skip the tutorial is the intended behaviour. 
AFAIK when you exit the editor your compounds are split among your new and old cells so if you didn't have any ATP before entering you don't have any after exiting, either.

**Comment by AndreLZGava** [comment] 2018-05-31 16:58
Like when I start the game if I use tutorial I can edit my organism because I have the resources, I don't want to take tutorial every time, but I would like to edit my organism anyway, so this behaviour forces me to take tutorial to edit in the beginning of the game.
Actualy when I edit my organism (first time) I start with ATP so when I end my edit I must had my ATP , but this is not happening to me. And I understood your point about editting and having ATP, but I think If I'm editing by organism its like a new generation, right? If its a new generation shoun't it begin with full ATP?

**Comment by hhyyrylainen** [comment] 2018-05-31 17:04
My plan for the tutorial in the next release is that you get hints and flashing buttons during normal gameplay so you won't get a free editor cycle.

Basically it is a new generation after you edit but at the same time it is modeled like a cell splitting so that's the reason you keep half of your compounds afterwards. 

I'm closing this as this is the intended behaviour. If you'd like to discuss the design behind this you can head on over to here: https://community.revolutionarygamesstudio.com/c/future-game/microbe-stage

**Closed by hhyyrylainen** 2018-05-31 17:04 UTC
