### ISSUE TITLE
Clicking on a species in Food Chain does not show the corresponding species in the evolutionary tree

### ISSUE THREAD

**Issue by stoptakingusernames** [Revolutionary-Games/Thrive#5650] opened 2024-11-03 22:21 UTC
### Describe the bug

When you click on a species in the Food-Chain tab, the Evolutionary tree opens with no species selected (or the last one you had selected in the evo-tree)

### To Reproduce

1. Go into food chain
2. Click any species

### Expected behaviour

I'm assuming the intended behaviour is that the species you clicked on would be the selected species in the evo-tree

### Screenshots

![image](https://github.com/user-attachments/assets/345d2d0a-4038-4d45-b028-cbeaf29be331)
![image](https://github.com/user-attachments/assets/4855e461-d737-42e5-84b0-0ee6a7ef6d28)

**Comment by hhyyrylainen** [comment] 2024-11-04 07:51
When implementing the new report I made the species clickable as that seems very natural thing to do when you want more information. I didn't have time to fully implement an info page for species so I had to pick something easy to do, and just opening the evolutionary tree was that. The actual feature is meant to eventually open a Thriveopedia page for that clicked species. So I'll close this as a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/4043

**Closed by hhyyrylainen** 2024-11-04 07:51 UTC
Labels: duplicate
