### ISSUE TITLE
Patch extinction box doesn't show current location correctly if you get several patch extinctions in a row.

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3547] opened 2022-07-17 08:41 UTC
Instead of showing the location you are currently in, it shows the initial location the last time you left the editor.

**Comment by hhyyrylainen** [comment] 2022-07-17 08:42
This is a duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3459

**Closed by hhyyrylainen** 2022-07-17 08:42 UTC
