### ISSUE TITLE
Passive absorption doesn't affect storage & colony

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3956] opened 2022-12-23 03:06 UTC
Now passive absorption seems to only affect individual cells, which is a weird thing: In theory if the external compound amount is positive, you should be able to absorb some whether or not you are able to reproduce. Plus this makes microbe colonies almost useless.

**Comment by hhyyrylainen** [comment] 2022-12-23 08:01
This is duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/3655
Multicellular colonies already have passive growth. Only non-multicellular colonies are not affected.

**Closed by hhyyrylainen** 2022-12-23 08:01 UTC
Labels: stage:microbe

**Comment by 84634E1A607A** [comment] 2022-12-23 08:10
Another thing I mentioned is that personally I think passive absorption should affect storage too. While this is open for discussion, this isn't part of #3655 so I think this issue may be reopened.

**Comment by hhyyrylainen** [comment] 2022-12-23 08:12
I'd say that warrants a game design discussion before considering reopening this issue as "Make passive absorption go to cell storage" (on dev discord or the dev forums).
