### ISSUE TITLE
Cells can be unstuck from the "colonies"

### ISSUE THREAD

**Issue by Leo512bit** [Revolutionary-Games/Thrive#2372] opened 2021-06-22 03:18 UTC
**Describe the bug**

Cells can be unstuck from the "colonies" but still be bound.

**To Reproduce**

Not really sure I originally thought it had something to do with the iron rocks but that was quickly disproven.

**Expected behavior**
I'm not sure if this is supposed to happen but I expect them to stay stuck and if they get lose they get unbounded.

**Screenshots**
![Screenshot 2021-06-21 201127](https://user-images.githubusercontent.com/64435704/122857224-fcb7d700-d2cc-11eb-8739-ce32cfa6c6da.jpg)

**System info (please complete the following information):**
- OS: Windows 10 20H2
- Graphics card AMD Vega 8 APU
- Thrive version 0.5.4

**Logs**

[log.log](https://github.com/Revolutionary-Games/Thrive/files/6690742/log.log)

**Comment by hhyyrylainen** [comment] 2021-06-22 05:36
Duplicate of: https://github.com/Revolutionary-Games/Thrive/issues/2310

**Closed by hhyyrylainen** 2021-06-22 05:36 UTC
